AWSTemplateFormatVersion: 2010-09-09
Description: creating VPC and private, Public subnets

Resources:
  mytestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: mytestVPC

  mytestPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref mytestVPC
      CidrBlock: 10.0.1.0/16
      AvailabilityZone: !Select []
      Tags:
      - Key: stack
        Value: production         